version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_HOST= mysql
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    # command: bash -c "while ! curl -s mysqldb:3306 > /dev/null; do echo waiting for xxx; sleep 3; done; start.sh"
    stdin_open: true
    tty: true

volumes: 
  db: